### ISSUE TITLE
Iryna : to-do-list

### ISSUE THREAD

**Issue by IrynaSobetska** [BF-FrontEnd-class/home#277]
- [x] [repo](https://github.com/IrynaSobetska/to-do-list) 
- [x] [live demo](https://irynasobetska.github.io/to-do-list/) 
- [planning](https://github.com/IrynaSobetska/to-do-list/tree/main/planning)
  - [x] constraints
  - [x] user personas
  - [x] backlog
  - [x] design
  - [x] development strategy
  - [x] retrospective
- [x] [project board](https://github.com/users/IrynaSobetska/projects/6/views/1)
