### ISSUE TITLE
Himanshi: Todo-list 

### ISSUE THREAD

**Issue by himanshisaxena** [BF-FrontEnd-class/home#280]
- [x] [repo](https://github.com/himanshisaxena/todo-list) 
- [x] [live demo](https://himanshisaxena.github.io/todo-list/) 
- [planning](https://github.com/himanshisaxena/todo-list/tree/main/planning)
  - [x] constraints
  - [x] user personas
  - [x] backlog
  - [x] design
  - [x] development strategy
  - [ ] retrospective
- [x] [project board](https://github.com/users/himanshisaxena/projects/9)
