### ISSUE TITLE
Inna: To-do-list

### ISSUE THREAD

**Issue by inna9Z** [BF-FrontEnd-class/home#282]
- [x] [repo](https://github.com/inna9Z/to-do-list) 
- [x] [live demo]( https://inna9z.github.io/to-do-list/) 
- [planning](https://github.com/inna9Z/to-do-list/tree/main/planning)
  - [x] constraints
  - [x] user personas
  - [x] backlog
  - [x] design
  - [x] development strategy
  - [x] retrospective
- [x] [project board](https://github.com/users/inna9Z/projects/3/views/1?layout=board)
