### ISSUE TITLE
Ervin: TODO-list 

### ISSUE THREAD

**Issue by ervinMamutov** [BF-FrontEnd-class/home#283]
- [x] [repo](https://github.com/ervinMamutov/todo-list) 
- [x] [live demo](https://ervinmamutov.github.io/todo-list/) 
- [planning](https://github.com/ervinMamutov/todo-list/tree/main/planning)
  - [x] constraints
  - [x] user personas
  - [x] backlog
  - [x] design
  - [x] development strategy
  - [ ] retrospective
- [x] [project board](https://github.com/users/ervinMamutov/projects/19/views/1)
