### ISSUE TITLE
Rekha: To-do-list

### ISSUE THREAD

**Issue by Rekhasriraman** [BF-FrontEnd-class/home#284]
- [x] [repo](https://github.com/Rekhasriraman/Todo-list) 
- [x] [live demo](https://rekhasriraman.github.io/Todo-list/) 
- [planning](https://github.com/Rekhasriraman/Todo-list/tree/main/planning)
  - [x] constraints
  - [x] user personas
  - [x] backlog
  - [x] design
  - [x] development strategy
- [x] [project board](https://github.com/users/Rekhasriraman/projects/8/views/1)
