### ISSUE TITLE
Preethi:To-do-list

### ISSUE THREAD

**Issue by PreethiTapati** [BF-FrontEnd-class/home#285]
- [x] [repo](https://github.com/PreethiTapati/To-do-list) 
- [x] [live demo](https://preethitapati.github.io/To-do-list/) 
- [planning]()
  - [x] constraints
  - [x] user personas
  - [x] backlog
  - [x] design
  - [x] development strategy
  - [x] retrospective
- [x] [project board](https://github.com/users/PreethiTapati/projects/5/views/1)
