### ISSUE TITLE
Maria: To-do-list

### ISSUE THREAD

**Issue by Mariya-go** [BF-FrontEnd-class/home#287]
- [x] [repo](https://mariya-go.github.io/My-todo-list/) 
- [x] [live demo](https://mariya-go.github.io/todo-list/) 
- [planning]()
  - [x] constraints
  - [x] user personas
  - [x] backlog
  - [ ] design
  - [x] development strategy
  - [ ] retrospective
- [x] [project board](https://github.com/users/Mariya-go/projects/16/views/1)
