### ISSUE TITLE
khalid: To-do-list

### ISSUE THREAD

**Issue by khalidkhan1212** [BF-FrontEnd-class/home#288]
- [x] [repo](https://github.com/Mileenka/To-do-list) 
- [x] [live demo](https://mileenka.github.io/To-do-list/) 
- [planning](https://github.com/Mileenka/To-do-list/tree/main/planning)
  - [ ] user personas
  - [ ] backlog
  - [ ] design
  - [ ] development strategy
  - [ ] retrospective
- [x] [project board](https://github.com/users/Mileenka/projects/9/views/1)
- [ ] Structure and content of the page
- [ ] Styling the website
- [ ] Interactive features and dynamic functionality
